load (includefile = 'stringsRearrangement.rb')
load ('../../test.rb')

t = Test.new(includefile)

t.test([["aba", "bbb", "bab"]],false)
t.test([["ab", "bb", "aa"]],true)
t.test([["q", "q"]],false)
t.test([["zzzzab", "zzzzbb", "zzzzaa"]],true)
t.test([["ab", "ad", "ef", "eg"]],false)
t.test([["abc", "bef", "bcc", "bec", "bbc", "bdc"]],true)
t.test([["abc", "abx", "axx", "abc"]],false)
t.test([["abc", "abx", "axx", "abx", "abc"]],true)
t.test([["f", "g", "a", "h"]],true)
t.test([["ff", "gf", "af", "ar", "hf"]],true)
t.test([["a", "b", "c"]],true)