load (includefile = 'buildPalindrome.rb')
load ('../../test.rb')

t = Test.new(includefile)

t.test(["abcdc"],"abcdcba")
t.test(["ababab"],"abababa")
t.test(["abba"],"abba")
t.test(["abaa"],"abaaba")
t.test(["aaaaba"],"aaaabaaaa")
t.test(["abc"],"abcba")
t.test(["kebab"],"kebabek")
t.test(["abccba"],"abccba")
t.test(["abcabc"],"abcabcbacba")
t.test(["cbdbedffcg"],"cbdbedffcgcffdebdbc")
t.test(["euotmn"],"euotmnmtoue")